version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./basys
      dockerfile: Dockerfile
    container_name: buildadmin-basys
    environment:
      NODE_ENV: dev
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-basys}?schema=public
      TZ: Asia/Shanghai
    ports:
      - "18000:18000"
    networks:
      - buildadmin-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  buildadmin-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16