/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "admin": {
        "dashboard": {
            "title": string;
            "welcome": string;
            "statistics": {
                "users": string;
                "orders": string;
                "revenue": string;
            };
        };
        "menu": {
            "home": string;
            "users": string;
            "orders": string;
            "settings": string;
        };
        "actions": {
            "create": string;
            "edit": string;
            "delete": string;
            "save": string;
            "cancel": string;
            "confirm": string;
        };
        "messages": {
            "deleteConfirm": string;
            "saveSuccess": string;
            "deleteSuccess": string;
            "operationFailed": string;
        };
    };
    "api": {
        "errors": {
            "notFound": string;
            "unauthorized": string;
            "forbidden": string;
            "badRequest": string;
            "internalError": string;
            "timeout": string;
        };
        "responses": {
            "created": string;
            "updated": string;
            "deleted": string;
            "retrieved": string;
        };
        "validation": {
            "invalidFormat": string;
            "duplicateEntry": string;
            "outOfRange": string;
            "invalidDate": string;
        };
        "database": {
            "connectionFailed": string;
            "queryError": string;
            "transactionFailed": string;
        };
    };
    "auth": {
        "admin": {
            "Group Name Arr": string;
            "Please use another administrator account to disable the current account!": string;
            "You have no permission to add an administrator to this group!": string;
        };
        "group": {
            "Super administrator": string;
            "No permission": string;
            "You cannot modify your own management group!": string;
            "name": string;
            "Please select rules": string;
            "You need to have all permissions of this group to operate this group~": string;
            "You need to have all the permissions of the group and have additional permissions before you can operate the group~": string;
            "Role group has all your rights, please contact the upper administrator to add or do not need to add!": string;
            "The group permission node exceeds the range that can be allocated": string;
            "The group has associated administrators and cannot be deleted": string;
        };
        "menu": {
            "type": string;
            "title": string;
            "name": string;
        };
        "rule": {
            "type": string;
            "title": string;
            "name": string;
        };
    };
    "common": {
        "Please login first": string;
        "You have no permission": string;
        "Username": string;
        "Password": string;
        "Nickname": string;
        "Email": string;
        "Mobile": string;
        "Captcha": string;
        "CaptchaId": string;
        "Please enter the correct verification code": string;
        "Captcha error": string;
        "Parameter {s} can not be empty": string;
        "Record not found": string;
        "No rows were added": string;
        "No rows were deleted": string;
        "No rows updated": string;
        "Update successful": string;
        "Added successfully": string;
        "Deleted successfully": string;
        "Parameter error": string;
        "File uploaded successfully": string;
        "No files were uploaded": string;
        "The uploaded file format is not allowed": string;
        "The uploaded image file is not a valid image": string;
        "The uploaded file is too large ({s}MiB), Maximum file size:{s}MiB": string;
        "No files have been uploaded or the file size exceeds the upload limit of the server": string;
        "Unknown": string;
        "Account not exist": string;
        "Account disabled": string;
        "Token login failed": string;
        "Username is incorrect": string;
        "Please try again after 1 day": string;
        "Password is incorrect": string;
        "You are not logged in": string;
        "Cache cleaned~": string;
        "{d} second{s} ago": string;
        "{d} minute{s} ago": string;
        "{d} hour{s} ago": string;
        "{d} day{s} ago": string;
        "{d} week{s} ago": string;
        "{d} month{s} ago": string;
        "{d} year{s} ago": string;
        "Please use the {s} field to sort before operating": string;
        "Topic format error": string;
        "Driver {s} not supported": string;
        "{d} second{s} after": string;
        "{d} minute{s} after": string;
        "{d} hour{s} after": string;
        "{d} day{s} after": string;
        "{d} week{s} after": string;
        "{d} month{s} after": string;
        "{d} year{s} after": string;
        "Please delete the child element first, or use batch deletion": string;
        "Configuration write failed: {s}": string;
        "Token expiration": string;
    };
    "routine": {
        "config": {
            "Basics": string;
            "Mail": string;
            "Config group": string;
            "Site Name": string;
            "Config Quick entrance": string;
            "Record number": string;
            "Version number": string;
            "time zone": string;
            "No access ip": string;
            "smtp server": string;
            "smtp port": string;
            "smtp user": string;
            "smtp pass": string;
            "smtp verification": string;
            "smtp sender mail": string;
            "Variable name": string;
            "Test mail sent successfully~": string;
            "This is a test email": string;
            "Congratulations, receiving this email means that your email service has been configured correctly": string;
            "Backend entrance rule": string;
            "Backend entrance": string;
            "The current page configuration item was updated successfully": string;
        };
    };
    "user": {
        "captcha": string;
        "captchaId": string;
        "Please input correct username": string;
        "Please input correct password": string;
        "Registration parameter error": string;
        "Login succeeded!": string;
        "Please enter the correct verification code": string;
        "You have already logged in. There is no need to log in again~": string;
        "Check in failed, please try again or contact the website administrator~": string;
        "Member center disabled": string;
        "Register type": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
